### ISSUE TITLE
Regular release updates of stats database

### ISSUE THREAD

**Issue by mpadge** [ropensci-review-tools/pkgstats#24]

**Comment by mpadge** [comment]
First data dump in [v0.0.3 release](https://github.com/ropensci-review-tools/pkgstats/releases/tag/v0.0.3).

## TODO

- [ ] Write function to locally download those data
- [ ] Use that function in `pkgcheck` to put data in `pkgcheck` cache directory, rather than using current `pkgcheck` data that are internally bundled and fixed
- [ ] Write GitHub action to automatically open issue every month to update these data.

**Comment by noamross** [comment]
- [ ] Document this process so someone else can run it.  Document before attempting to add more automation.
