### ISSUE TITLE
CRAN release

### ISSUE THREAD

**Issue by mpadge** [ropensci-review-tools/pkgstats#37]

**Comment by mpadge** [comment]
From CRAN:

> Thanks,
>
> The Description field is intended to be a (one paragraph) description of what the package does and why it may be useful. Please add more details about the package functionality and implemented methods in your Description text.
>
> Please add \value to .Rd files regarding exported methods and explain the functions results in the documentation. Please write about the structure of the output (class) and also what the output means. (If a function does not return a value, please document that too, e.g. \value{No return value, called for side effects} or similar)
>
> Missing Rd-tags:
>     ctags_install.Rd: \value
>     desc_stats.Rd: \value
>     rd_stats.Rd: \value
>     tags_data.Rd: \value
>
> Please make sure that you do not change the user's options, par or working directory. If you really have to do so within functions, please ensure with an *immediate* call of on.exit() that the settings are reset when the function is exited. e.g.:
> ...
> oldwd <- getwd()           # code line i
> on.exit(setwd(oldwd))        # code line i+1
> ...
> setwd(...)            # somewhere after
> ...
> e.g.: tag-data-ctags.R
> If you're not familiar with the function, please check ?on.exit. This function makes it possible to restore options before exiting a function even if the function breaks. Therefore it needs to be called immediately after the option change within a function.
>
> You are using installed.packages():
> "This needs to read several files per installed package, which will be slow on Windows and on some network-mounted file systems.
> It will be slow when thousands of packages are installed, so do not use it to find out if a named package is installed (use find.package or system.file) nor to find out if a package is usable (call requireNamespace or require and check the return value) nor to find details of a small number of packages (use packageDescription)."
> [installed.packages() help page]

---

## TODO

- [ ] Fix DESC
- [ ] Fix missing Rd return values
- [ ] Use `on.exit()` for options, or remove use of options entirely
- [ ] Use `find.package()` instead of `installed.packages()`

**Comment by mpadge** [comment]
https://cran.r-project.org/package=pkgstats

**Comment by mpadge** [comment]
Argh, package already fails tests on windows machines because of the main vignette. Re-opening to update that to not presume any ability to install anything on CRAN windows machines.
