### ISSUE TITLE
Get back on CRAN

### ISSUE THREAD

**Issue by mpadge** [ropensci-review-tools/pkgstats#55]
Got kicked off because package downloads binary objects in https://github.com/ropensci-review-tools/pkgstats/blob/main/configure#L4 and https://github.com/ropensci-review-tools/pkgstats/blob/main/tools/winlibs.R#L2-L3. Need to remove these and rewrite as optional internal functionality for windows and macos.

**Comment by mpadge** [comment]
Can now use the [`ami` package](https://github.com/briandconnelly/ami) function `on_cran` via https://github.com/briandconnelly/ami/issues/14 to auto-download and install ctags binaries for windows + macos when `!ami::on_cran()`.

**Comment by mpadge** [comment]
Can't submit until resolution of of https://github.com/r-lib/cpp11/issues/355 ...

**Comment by mpadge** [comment]
Getting close. This is CRAN response to attempted re-submission:

> Please add \value to .Rd files regarding exported methods and explain the functions results in the documentation. Please write about the structure of the output (class) and also what the output means. (If a function does not return a value, please document that too, e.g. \value{No return value, called for side effects} or similar)
Missing Rd-tags:
     pkgstats_cran_current_from_full.Rd: \value
For more details: [<https://contributor.r-project.org/cran-cookbook/docs_issues.html#missing-value-tags-in-.rd-files>](https://contributor.r-project.org/cran-cookbook/docs_issues.html#missing-value-tags-in-.rd-files)
>
> \dontrun{} should only be used if the example really cannot be executed (e.g. because of missing additional software, missing API keys, ...) by the user. That's why wrapping examples in \dontrun{} adds the comment ("# Not run:") as a warning for the user. Does not always seem necessary. Please replace \dontrun with \donttest.
Please unwrap the examples if they are executable in < 5 sec, or replace dontrun{} with \donttest{}.
For more details: [<https://contributor.r-project.org/cran-cookbook/general_issues.html#structuring-of-examples>](https://contributor.r-project.org/cran-cookbook/general_issues.html#structuring-of-examples)
>
> Please ensure that your functions do not write by default or in your examples/vignettes/tests in the user's home filespace (including the package directory and getwd()). This is not allowed by CRAN policies. Please omit any default path in writing functions. In your examples/vignettes/tests you can write to tempdir().
-> e.g.: R/ctags-install.R; R/gtags-install.R; ...
For more details: [<https://contributor.r-project.org/cran-cookbook/code_issues.html#writing-files-and-directories-to-the-home-filespace>](https://contributor.r-project.org/cran-cookbook/code_issues.html#writing-files-and-directories-to-the-home-filespace)
>
> Please fix and resubmit.

## TODO

- [ ] Add return val description to `pkgstats_cran_current_from_full`
- [ ] Replace `dontrun` with `donttest`.
- [ ] Fix `ctags/gtags-install` write locations
